// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAT1ixWrgL3ScDwAhwqLn9eS3t_IjesVUE',
    appId: '1:240070260442:web:cc49c4f40e61ca19af17e3',
    messagingSenderId: '240070260442',
    projectId: 'flashcard-70248',
    authDomain: 'flashcard-70248.firebaseapp.com',
    storageBucket: 'flashcard-70248.firebasestorage.app',
    measurementId: 'G-M6613QJFRP',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDNzwi4SeDl8OW2Ck66nWcmtCX7WKTRHCw',
    appId: '1:240070260442:android:0ecbc2b9b431bf30af17e3',
    messagingSenderId: '240070260442',
    projectId: 'flashcard-70248',
    storageBucket: 'flashcard-70248.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDivQ6Z61CqTkvE6QIClx_UdHOwLQYDt18',
    appId: '1:240070260442:ios:bb32462a847a6d1aaf17e3',
    messagingSenderId: '240070260442',
    projectId: 'flashcard-70248',
    storageBucket: 'flashcard-70248.firebasestorage.app',
    iosBundleId: 'com.example.efeflascard',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDivQ6Z61CqTkvE6QIClx_UdHOwLQYDt18',
    appId: '1:240070260442:ios:bb32462a847a6d1aaf17e3',
    messagingSenderId: '240070260442',
    projectId: 'flashcard-70248',
    storageBucket: 'flashcard-70248.firebasestorage.app',
    iosBundleId: 'com.example.efeflascard',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAT1ixWrgL3ScDwAhwqLn9eS3t_IjesVUE',
    appId: '1:240070260442:web:9db483658516d739af17e3',
    messagingSenderId: '240070260442',
    projectId: 'flashcard-70248',
    authDomain: 'flashcard-70248.firebaseapp.com',
    storageBucket: 'flashcard-70248.firebasestorage.app',
    measurementId: 'G-W6945B5SYD',
  );
}
